guardian/data-lake-alerts

- src/main/scala/com/gu/mobiledatalakealerts/AwsCredentials.scala
This should allow the correct credentials to be loaded within a lambda (currently it has just been running locally).
> Add environment variable credentials for lambda compatibility

- src/main/scala/com/gu/mobiledatalakealerts/Athena.scala
- src/main/scala/com/gu/mobiledatalakealerts/AwsCredentials.scala
- src/main/scala/com/gu/mobiledatalakealerts/Features.scala
- src/main/scala/com/gu/mobiledatalakealerts/Lambda.scala
Coping with beta versions is proving trickier than I expected, so I've decided to get this running for production versions first.
This PR removes any beta specific code. It also refactors things slightly, to incorporate @alexduf's suggestion that the function for checking query results is located with the query (inside `Feature`).
> Refactor and temporarily remove beta functionality

- cfn.yaml
- src/main/scala/com/gu/datalakealerts/Athena.scala
This PR adds the correct IAM permissions for the lambda (at the moment it just needs to be able to query clean.pageviews).
> Allow lambda to query clean.pageviews

- cfn.yaml
Allows us to schedule a monitoring/alerting task on weekdays at 6am.
This will monitor friction_screen impressions on iOS and Android.
> Schedule monitoring for Android friction screen

- cfn.yaml
- src/main/scala/com/gu/datalakealerts/Athena.scala
The lambda has timed out a few times whilst waiting for the Athena query to complete.
This is quite odd because according to Athena's History tab, the queries always appear to complete successfully in ~15 seconds.
I don't really understand this problem yet - I've never seen it when testing but it seems to happen quite consistently when this lambda is run on the early morning schedule. This PR extends the timeout and adds a new log line to try and help me to understand what's going wrong...
> Add debug statement and increase timeout

- cfn.yaml
- src/main/scala/com/gu/datalakealerts/Athena.scala
This was broken due to some changes to the workgroups in the Ophan account.
[Override client-side settings ](https://docs.aws.amazon.com/athena/latest/ug/workgroups-settings-override.html)has been enabled, which means that query results will now always be written to `/primary` instead of `/data-lake-alerts`.
I think there would be some advantages to using a dedicated workgroup for this lambda (and perhaps other 'machine users'), so have added a note to remind myself to consider this for another PR.
> Fix permissions after workgroup changes

- src/main/scala/com/gu/datalakealerts/Lambda.scala
This is slightly better than having to hardcode values in the `TestIt` object.
> Pass platform and feature as arguments for testing purposes

- README.md
Basic documentation to help developers add their own alerts.
Unfortunately this shows that there is still plenty of work required to make it easier to add monitoring for new features!
> Add some documentation to help teams add their own monitoring tasks

- cfn.yaml
- src/main/scala/com/gu/datalakealerts/Features.scala
I've also renamed the feature `Epic` from `EpicAndroidFeature` since it handles both platforms.
Unsure why `ab.completed = False` is required for the iOS query but `ab.completed = True` is required for the Android query, and also why "mp3" has anything to do with anything.
> Add query for iOS epic

- cfn.yaml
I've just created a `PROD` environment, but I don't want to run twice as many queries unnecessarily. Consequently this PR disables the scheduled event in `CODE`.
I still think it's important to have a `CODE` environment of some sort, so that CloudFormation changes can be properly tested. This is the best compromise I could think of at the moment.
> Disable scheduling in the CODE environment

- README.md
- build.sbt
- src/main/scala/com/gu/datalakealerts/Lambda.scala
This PR makes it easier to test alerts when running locally.
Previously developers would have to obtain the Anghammarad SNS topic, set an environment variable and then send an email to their whole team in order to test an alert. This is obviously undesirable for a number of reasons!
Now we read the SNS topic from AWS Parameter store when running locally (which means less effort/frustration for developers who want to send a test alert). We also override the stack which is passed to Anghammarad in DEV/CODE, so that test alerts are sent to a dedicated Google Group (which means there is less spam for teams).
All of the Parameter Store values are initialised lazily. These `lazy val`s should never be accessed when running inside a lambda, so this should only affect local development.
> Allow developers to send alerts locally without spamming

- cfn.yaml
Prior to this PR, checking the logs was the only way to distinguish between a case where all monitoring checks ran successfully (i.e. no alerts were sent because no alerts should be sent) and the case where this lambda fails (i.e. no alerts were sent because something went wrong). This PR solves that problem by adding alerting for this alerting service.
> Add meta-alerting

- cfn.yaml
I forgot to change the alert name based on the stage, which meant that [this change](https://github.com/guardian/data-lake-alerts/pull/19) couldn't be deployed to `CODE` and `PROD` at the same time 🤦‍♂
> Create different alarm for each stage

- build.sbt
- src/main/scala/com/gu/datalakealerts/AlertInformation.scala
- src/main/scala/com/gu/datalakealerts/Features.scala
- src/main/scala/com/gu/datalakealerts/Lambda.scala
- src/test/scala/com.gu.datalakealerts/AlertInformationTest.scala
Incorporates some feedback from @alexanderedge and @davidfurey.
- Improves logging in successful case (no alert sent), to increase trust in the monitoring tool! You now get a log line like: `2019-08-14 15:53:33 [run-main-0]  INFO  Lambda$:113 - Monitoring ran successfully for friction_screen on android. No problems were detected.
Actual impressions: 52250 | Expected impressions: 35000 | Percentage: 49% above the threshold.`
- If an alert is sent, includes the amount that we fell below the minimum expected threshold (as a percentage)
- Makes additional alert information mandatory - there's not much value in sending alerts which don't have the required debug info
- Adds a few unit tests
> Improve additional alert information (and make it mandatory)

- cfn.yaml
There have been several occasions in the last few weeks where yesterday's page view data has not been available first thing in the morning.
This is a pain because:
1) we get several false alarms
2) we have to remember to manually re-run each monitoring task once the table has been updated
This PR edits the schedule so that we run our checks later in the day (which affords the Data Tech team some time to fix/re-run failed jobs). It might also be worth adding a check for staleness before running our own queries, but this simple change should mitigate our problems slightly...
> Edit schedule so that monitoring tasks run later

- src/main/scala/com/gu/datalakealerts/Features.scala
Before Braze, we expected around 617315 impressions a day. I think it's around 66% of users that are eligible for Braze (have accepted personalised advertising, and have 'limit ad tracking' turned off), so let's look for around 30% of the original number on Olgil.
> Decrease expected Olgil epic impressions for iOS

- cfn.yaml
We've temporarily stopped serving epics via Braze on iOS, so I'm disabling this monitoring task for now (to avoid noise / false alarms).
As it happens, there's a [limitation](https://github.com/guardian/data-lake-alerts/pull/26#pullrequestreview-293047561) which was preventing us from performing the same monitoring task for Android. Since there's now a free target slot, we might as well start running the Android version of the check instead of removing the target completely. 
It will be trivial to reenable the iOS version of the check when necessary (if my refactor to allow more targets is complete, it will 'just work'; if not we can temporarily add a second event rule to workaround the limitation).
> Disable iOS Braze Epic Monitoring (and enable Android Braze Epic Monitoring)

- README.md
- cfn.yaml
- riff-raff.yaml
- src/main/scala/com/gu/datalakealerts/SchedulerLambda.scala
- src/main/scala/com/gu/datalakealerts/WorkerLambda.scala
Unfortunately there is a [5 target limit per CloudWatch Event Rule](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html#limits_cloudwatch_events), which means that we need a new approach for scheduling monitoring tasks.
The approach I'm working on will be something like this:
This PR is the first part of that restructure. It adds a very basic version of new Scheduler Lambda (which doesn't do any real work yet) and refactors the existing Worker Lambda accordingly. 
For now the scheduling is unchanged and the worker is still invoked via the scheduled event (this will be changed in a subsequent PR).
> Add scheduler lambda

- build.sbt
- src/main/scala/com/gu/datalakealerts/Athena.scala
- src/main/scala/com/gu/datalakealerts/AwsCredentials.scala
- src/main/scala/com/gu/datalakealerts/Features.scala
- src/main/scala/com/gu/datalakealerts/InvokeWorker.scala
- src/main/scala/com/gu/datalakealerts/MonitoringEvent.scala
- src/main/scala/com/gu/datalakealerts/SchedulerLambda.scala
- src/main/scala/com/gu/datalakealerts/WorkerLambda.scala
Continues the work started in: https://github.com/guardian/data-lake-alerts/pull/28.
Note that the final part of this work (i.e. updating the CloudFormation so that the scheduler is invoked, instead of the worker) will follow in another PR.
> Allow scheduler to invoke the worker 

- README.md
- cfn.yaml
This is the final part of a restructure (see also https://github.com/guardian/data-lake-alerts/pull/28 and https://github.com/guardian/data-lake-alerts/pull/29) which moves us to this architecture:
Although this work was primarily undertaken to work around an AWS limitation (5 targets per rule), it has also made it easier to add new monitoring tasks. 
The Scheduler Lambda now automatically figures out the input JSON for a feature, meaning that no CFN changes are required when adding new monitoring.
> Trigger the Scheduler Lambda via the CloudWatch Event Rule

- cfn.yaml
Now that we are submitting more queries to AWS concurrently, the worker lambda is often timing out before the results of its query are available. Although a query is listed as `RUNNING` straight after submission:
> RUNNING indicates that the query has been submitted to the service, and Athena will execute the query *as soon as resources are available*.
If AWS isn't able to execute all of the queries within 180 seconds, we see alerts due to timeouts (which are annoying). These timeouts currently result in the query being automatically retried by AWS (which is wasteful, as we are often paying to run the same query more than once).
This PR is a short term measure to buy us some time, and avoid the alerts/retries mentioned above. The proper solution to this problem requires a little more …
> Increase timeout for worker lambda

- src/main/scala/com/gu/datalakealerts/Features.scala
I've added both Braze and Olgil monitoring for banners but since the Braze banner is not implemented yet I left its threshold at 0 and did not add it to the `allFeaturesWithMonitoring` list.
The `olgil_banner` threshold number is yesterday's impressions on all app versions, halved.
I tested the Olgil one locally using a fake minimum threshold (a much too large one) and got the alert in the Anghammarad google group.
I'm not sure if adding the Braze one now as I've done is a good idea or not, so I could use some feedback on that.
> Add iOS Banner monitoring

- src/main/scala/com/gu/datalakealerts/Athena.scala
- src/main/scala/com/gu/datalakealerts/Features.scala
- src/main/scala/com/gu/datalakealerts/apps/ResultHandler.scala
This [commit](https://github.com/guardian/data-lake-alerts/commit/14746e47928572cb6c4bd7ad934d8aa4f956bcd4) addresses [this feedback](https://github.com/guardian/data-lake-alerts/pull/32#discussion_r337900965).
This [commit](https://github.com/guardian/data-lake-alerts/commit/509db3c3280b72acadabcfb90dd9cb37596ba099), removes some unnecessary usages of `override`.
> Remove duplication when checking results

- src/main/scala/com/gu/datalakealerts/Features.scala
I ran queries on the data lake to see how many impressions were made yesterday for the Braze Banner and Olgil Banner. I found **5786 Braze banner** and **34077 Olgil banner** impressions and I have divided set the threshold as half of these. 
It does seem like a drop in the number of impressions compared to what was previously set as the Olgil banner impression level.
> GLA-1579-Braze-banner-prod-monitoring

- src/main/scala/com/gu/datalakealerts/Features.scala
Since moving the logic for displaying a friction screen into Braze, friction screen impressions are no longer evenly distributed:
To prevent lots of false alarms, I'm dropping the expected threshold until the distribution levels out again. I'll create a card to remind us to revisit this in 2020.
> Drop expected friction screen impressions for Android

- README.md
- src/main/scala/com/gu/datalakealerts/Checks.scala
- src/main/scala/com/gu/datalakealerts/Features.scala
- src/main/scala/com/gu/datalakealerts/Platforms.scala
- src/main/scala/com/gu/datalakealerts/ResultInformation.scala
- src/main/scala/com/gu/datalakealerts/WorkerLambda.scala
- src/main/scala/com/gu/datalakealerts/apps/ResultHandler.scala
- src/test/scala/com.gu.datalakealerts/ResultInformationTest.scala
This PR allows us to run multiple checks against the results of a single query. This means that we can run additional checks (e.g. confirming that things still work as expected on the [most recent beta versions](https://mobile.guardianapis.com/static/reserved-paths/ios-live-app/recent-beta-releases.json)), without duplicating lots of code. It could also help us to save [money](https://aws.amazon.com/athena/pricing/), as we can now run a single Athena query and perform multiple checks against its results.
> Add support for running multiple checks against a single query

- cfn.yaml
- src/main/scala/com/gu/datalakealerts/Features.scala
Until now all checks have assumed that the day of the week has no impact on the expected number of impressions. Customer Optimisation have changed the rules for the friction screen, which means this assumption is no longer valid.
Because of the aforementioned assumption, we didn't previously run checks over the weekend (prior to this PR the numbers for Friday and Saturday were never being checked). Now that Friday and Saturday have special importance, I decided that we ought to be checking the data for those days! This incurs a small cost (because we are running more lambda invocations and more queries against Athena), but I think it's better than missing bugs/config issues which could potentially only affect these days.
I've confirmed that the new cron is correct by deploying to `CODE`:
> Add support for new friction screen rules

- src/main/scala/com/gu/datalakealerts/Features.scala
Fixes a bug with https://github.com/guardian/data-lake-alerts/pull/40.
When estimating thresholds, we always need awareness of _yesterday_'s day of the week, not the day of the week at runtime.
> Fix peak/off-peak handling

- src/main/scala/com/gu/datalakealerts/Features.scala
The Customer Optimisation team are regularly using Braze to test changes to the display rules for the friction screen and the banner. As a result, alerts related to these acquisition channels have become noisy and unreliable. 
Monitoring these acquisition channels is also less important than it was before, because the Customer Optimisation team are regularly using the dashboard to check performance. 
Consequently, this PR removes alerts related to the number of banners/friction screen impressions initiated by Braze.
> Remove redundant alerts

- cfn.yaml
There have been too many false alarms from this service recently. 
I'm disabling these alerts until I have time to make the necessary changes to prevent regular false alarms from happening.
> Disable schedule temporarily
